[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
CheckInterval = '10s'
Host = 'localhost'
ServerBindAddr = ''
Port = 49992
Protocol = 'http'
StartupMsg = 'device simple started'
Timeout = 20000
ConnectedRetries = 20
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Clients]
    [Clients.Data]
    Protocol = 'http'
    Host = 'localhost'
    Port = 48080

    [Clients.Metadata]
    Protocol = 'http'
    Host = 'localhost'
    Port = 48081

    [Clients.Logging]
    Protocol = 'http'
    Host = 'localhost'
    Port = 48061

[Device]
DataTransform = true
InitCmd = ''
InitCmdArgs = ''
MaxCmdOps = 128
MaxCmdValueLen = 256
RemoveCmd = ''
RemoveCmdArgs = ''
ProfilesDir = './res'
UpdateLastConnected = false
    [Device.Discovery]
    Enable = false
    Interval = '30s'

[Logging]
EnableRemote = false
File = ''

[[DeviceList]]
    name = 'Random'
    Profile = 'Random'
    Description = 'Random Number Generator Device'
    Labels = ['random','test','qinyong']
    [DeviceList.Protocols]
        [DeviceList.Protocols.Other]
        Address = 'Random'
        Port = 300
    [[DeviceList.AutoEvents]]
        Resource = 'Random'
        OnChange = false
        Frequency = '10s'