[Writable]
ScheduleIntervalTime=500
LogLevel='INFO'

[Clients]
    [Clients.Logging]
    Host='localhost'
    Port=48061
    Protocol='http'

[Logging]
EnableRemote = false
File = ''

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Databases]
  [Databases.Primary]
  Host = 'localhost'
  Name = 'scheduler'
  Password = 'password'
  Port = 6379
  Username = 'scheduler'
  Timeout = 5000
  Type = 'redisdb'

[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'localhost'
Port = 48085
Protocol = 'http'
StartupMsg = 'This is the Support Scheduler Microservice'
Timeout = 5000

