[Writable]
ResendLimit = 2
LogLevel = 'INFO'
 
[Service]
BootTimeout = 30000
ClientMonitor = 15000
CheckInterval = '10s'
Host = 'localhost'
Port = 48060
Protocol = 'http'
ReadMaxLimit = 1000
StartupMsg = 'This is the Support Notifications Microservice'
Timeout = 5000
 
[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'
 
[Logging]
EnableRemote = false
File = ''
 
[Clients]
  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061
 
[Databases]
  [Databases.Primary]
  Host = 'localhost'
  Name = 'notifications'
  Password = 'password'
  Port = 6379
  Username = 'notifications'
  Timeout = 5000
  Type = 'redisdb'
 
[Smtp]
Host = 'smtp.163.com'
Password = '20010215b'
Port = 25
Sender = '18398079772@163.com'
Subject = 'EdgeX Notification Test'